Separate chain calls
yiisoft/active-record pull request #182
Opened 2022-05-17 06:17 UTC by sankaest

| Q             | A
| ------------- | ---
| Readability fix | according to https://github.com/yiisoft/docs/issues/155, chain calls must be put on separate lines

2022-05-19 10:42 UTC, vjik requested changes
Why added `tests/Data/Runtime/yiitest.sq3` ? Seems, it needs to be deleted.

2022-05-19 10:42 UTC, vjik commented on src/Redis/LuaScriptBuilder.php
> +            ':a:');
```suggestion
        $key = $this->quoteValue(
            $query
                ->getARInstance()
                ->keyPrefix() .
            ':a:'
        );
```

2022-05-19 10:42 UTC, vjik commented on tests/Pgsql/ActiveRecordTest.php
> +        );
```suggestion
        $this->assertTrue(
            $boolARQuery
                ->where(['bool_col' => true])
                ->one()->bool_col
        );
```

2022-05-19 10:42 UTC, vjik commented on tests/Pgsql/ActiveRecordTest.php
> +        );
```suggestion
        $this->assertFalse(
            $boolARQuery
                ->where(['bool_col' => false])
                ->one()->bool_col
        );
```

2022-05-19 10:42 UTC, vjik commented on tests/ActiveQueryTest.php
> +            ->all();
```suggestion
        $orders2 = $customer
            ->getOrders2()
            ->asArray()
            ->all();
```

2022-05-20 07:08 UTC, vjik commented
@sankaest what about `tests/Data/Runtime/yiitest.sq3` ?

2022-05-20 08:08 UTC, sankaest commented
@vjik I don't know where it came from :( . I have not added it, but maybe somehow accidentally, as I still quite new to git/gitHub and still learning (sometimes by deleting whole changes I made, you know - checkout/master, brrrr :) ).
I delete this file.

2022-05-20 11:13 UTC, vjik commented
> @vjik I don't know where it came from :( . I have not added it, but maybe somehow accidentally, as I still quite new to git/gitHub and still learning (sometimes by deleting whole changes I made, you know - checkout/master, brrrr :) ).
> I apologize and I delete this file.

It's OK. You gain experience!

2022-05-20 11:14 UTC, vjik approved these changes

2022-05-22 09:00 UTC, merged