Allow to specify the table name dynamically for `ActiveRecord::class`.
yiisoft/active-record pull request #203
Opened 2022-11-07 23:26 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

2022-11-20 15:42 UTC, xepozz requested changes

2022-11-20 15:42 UTC, xepozz commented on src/ActiveRecordInterface.php
> +     * Example static method:
This is not about static method

2022-11-20 15:42 UTC, xepozz commented on tests/ActiveRecordFactoryTest.php
> +        $this->assertInstanceOf(Customer::class, $customerAR);
```suggestion
        $customerAR = $this->arFactory->createAR(Customer::class, 'custom_table_name');
        $tableName = $customerAR->getTableName();

        $this->assertSame('custom_table_name', $tableName);
        $this->assertInstanceOf(Customer::class, $customerAR);
```

`customer` is default table name rely on class name

2022-11-27 23:19 UTC, xepozz approved these changes

2022-11-28 20:17 UTC, darkdef commented on src/ActiveQuery.php
> +        return $this->arFactory->createAR($this->arClass, $this->tableName, $this->db);
May be tableName as last parameter?

2022-11-30 20:52 UTC, xepozz commented
So let's merge it?

2022-11-30 20:56 UTC, darkdef approved these changes

2022-11-30 20:56 UTC, merged