implement the interface ArrayableInterface for BaseActiveRecord
yiisoft/active-record pull request #273
Opened 2023-12-09 08:55 UTC by niqingyang

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | https://github.com/yiisoft/active-record/issues/272#issue-2021848888 # fixed by the PR

2023-12-09 12:01 UTC, terabytesoftw commented
The tests fails.

2023-12-10 03:33 UTC, Tigrov requested changes
`ActiveRecordInterface::fields()` also should be removed as a part of `ArrayableInterface`

https://github.com/niqingyang/active-record/blob/fa7c4cb1144c5d2190ddeb37d4c773bc4921312b/src/ActiveRecordInterface.php#L89-L95

2023-12-10 03:33 UTC, Tigrov commented on src/BaseActiveRecord.php
> +    public function toArray(array $fields = [], array $expand = [], bool $recursive = true): array
```suggestion
```
Looks like implementation from `ArrayableTrait` also good.

2023-12-11 02:03 UTC, Tigrov requested changes

2023-12-11 02:03 UTC, Tigrov commented on tests/Driver/Oracle/ActiveRecordTest.php
> +    }
```suggestion
```

`\Yiisoft\ActiveRecord\Tests\Driver\Oracle\ActiveRecordTest` inherits from `\Yiisoft\ActiveRecord\Tests\ActiveRecordTest` where the test already exists.

2023-12-11 02:03 UTC, Tigrov commented on tests/Driver/Pgsql/ActiveRecordTest.php
> +    }
```suggestion
```

`\Yiisoft\ActiveRecord\Tests\Driver\Pgsql\ActiveRecordTest` inherits from `\Yiisoft\ActiveRecord\Tests\ActiveRecordTest` where the test already exists.

2023-12-11 08:51 UTC, Tigrov requested changes
👍

2023-12-11 08:51 UTC, Tigrov commented on src/ActiveRecordInterface.php
> +interface ActiveRecordInterface extends ArrayableInterface
```suggestion
interface ActiveRecordInterface
```

It is better to move ArrayableInterface to implementation of BaseActiveRecord as you did before

2023-12-11 08:51 UTC, Tigrov commented on src/BaseActiveRecord.php
>  abstract class BaseActiveRecord implements ActiveRecordInterface, IteratorAggregate, ArrayAccess
```suggestion
abstract class BaseActiveRecord implements ActiveRecordInterface, IteratorAggregate, ArrayAccess, ArrayableInterface
```

2023-12-11 09:22 UTC, niqingyang commented on src/ActiveRecordInterface.php
> +interface ActiveRecordInterface extends ArrayableInterface
ok

2023-12-11 09:22 UTC, niqingyang commented on src/BaseActiveRecord.php
>  abstract class BaseActiveRecord implements ActiveRecordInterface, IteratorAggregate, ArrayAccess
ok

2023-12-11 09:25 UTC, Tigrov commented on src/ActiveRecordInterface.php
> +    public function toArray(array $fields = [], array $expand = [], bool $recursive = true): array;
As it is a part of `ArrayableInterface`, the methods `fields()` and `toArray()` no needed in `ActiveRecordInterface`

2023-12-11 15:23 UTC, niqingyang commented on src/ActiveRecordInterface.php
> +    public function toArray(array $fields = [], array $expand = [], bool $recursive = true): array;
ok

2023-12-13 02:08 UTC, Tigrov approved these changes

2023-12-16 05:49 UTC, merged

2023-12-16 05:50 UTC, Tigrov commented
Thank you 👍

2023-12-16 08:43 UTC, niqingyang commented
> Thank you 👍

🤝