Update the comments of the method createQueryTo in ActiveRecordFactory so that the IDE can automatically identify the specific class of ActiveRecord
yiisoft/active-record pull request #280
Opened 2023-12-19 13:35 UTC by niqingyang

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2023-12-20 12:12 UTC, samdark approved these changes

2023-12-21 08:22 UTC, xepozz approved these changes

2024-01-02 09:35 UTC, niqingyang commented
> Also need to check that tests passed

🎉 It has been tests passed

2024-01-02 09:53 UTC, Tigrov requested changes

2024-01-02 09:53 UTC, Tigrov commented on src/ActiveQuery.php
> +     * @param class-string $arClass
```suggestion
     * @param string $arClass
```

Psalm annotations should be specified with `psalm-` prefix, e.g. `@psalm-param`. For `$arClass` it is already exists.
PHPDoc type annotations specified without `psalm-` prefix should be correct, e.g. `@param string`

2024-01-02 09:53 UTC, Tigrov commented on src/ActiveRecordFactory.php
> +     * @param class-string<T> $arClass active record class.
```suggestion
     * @param string $arClass active record class.
```

2024-01-02 09:53 UTC, Tigrov commented on src/BaseActiveRecord.php
> +     * @param class-string<T> $class The class name of the related record
```suggestion
     * @param string $class The class name of the related record
```

2024-01-02 09:53 UTC, Tigrov commented on src/BaseActiveRecord.php
> +     * @psalm-param class-string<T> $arClass
```suggestion
     * @psalm-param class-string<ActiveRecordInterface> $arClass
```

2024-01-02 09:53 UTC, Tigrov commented on src/BaseActiveRecord.php
> +     * @param class-string<T> $class The class name of the related record.
```suggestion
     * @param string $class The class name of the related record.
```

2024-01-02 09:53 UTC, Tigrov commented on src/BaseActiveRecord.php
> +     * @psalm-param class-string<T> $arClass
```suggestion
     * @psalm-param class-string<ActiveRecordInterface> $arClass
```

2024-01-02 09:53 UTC, Tigrov commented on src/BaseActiveRecord.php
> +     * @psalm-param class-string<T> $arClass
```suggestion
     * @psalm-param class-string<ActiveRecordInterface> $arClass
```

2024-01-02 09:53 UTC, Tigrov commented on src/BaseActiveRecord.php
> +     * @param class-string<T> $arClass The class name of the related record.
```suggestion
     * @param string $arClass The class name of the related record.
```

2024-01-02 09:53 UTC, Tigrov commented on src/BaseActiveRecord.php
> +     * @psalm-param class-string<T> $arClass
```suggestion
     * @psalm-param class-string<ActiveRecordInterface> $arClass
```

2024-01-03 07:18 UTC, Tigrov approved these changes
👍

2024-01-03 07:19 UTC, merged