More clean code, add typehints, fix phpdocs, add new methods.
yiisoft/active-record pull request #95
Opened 2020-09-14 15:11 UTC by terabytesoftw

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

2020-09-15 23:05 UTC, samdark requested changes

2020-09-15 23:05 UTC, samdark commented on src/ActiveDataProvider.php
> +class ActiveDataProvider extends DataReaderProvider
How about making it similar to interface?

```suggestion
class ActiveDataReader extends DataReaderProvider
```

2020-09-15 23:05 UTC, samdark commented on src/ActiveDataProvider.php
> +            //$query->addOrderBy($sort->getOrder());
Doesn't look alright.

2020-09-19 17:00 UTC, terabytesoftw commented on src/ActiveDataProvider.php
> +            //$query->addOrderBy($sort->getOrder());
Fixed.

2020-09-19 17:00 UTC, terabytesoftw commented on src/ActiveDataProvider.php
> +class ActiveDataProvider extends DataReaderProvider
Fixed

2020-09-19 19:38 UTC, samdark approved these changes

2020-09-20 13:36 UTC, merged